name: Camilo Coolify PostgreSQL
version: "0.1.0"
upstream: "15-alpine"
slug: camilo_coolify_postgres
description: PostgreSQL backend for the Camilo Coolify add-on.
url: https://github.com/camiloconcha/homeassistant-addons
arch:
  - amd64
  - aarch64
startup: system
boot: auto
init: true
stage: experimental
backup: cold
options:
  postgres_db: coolify
  postgres_user: coolify
  postgres_password: ""
schema:
  postgres_db: str
  postgres_user: str
  postgres_password: password
