name: Camilo Coolify Redis
version: "0.1.0"
upstream: "7-alpine"
slug: camilo_coolify_redis
description: Redis backend for the Camilo Coolify add-on.
url: https://github.com/camiloconcha/homeassistant-addons
arch:
  - amd64
  - aarch64
startup: system
boot: auto
init: true
stage: experimental
backup: cold
options:
  redis_password: ""
schema:
  redis_password: password
