name: camilo_n8n
version: "1.105.3"
upstream: 1.62.4
slug: camilo_n8n
description: >-
  n8n is an extendable workflow automation tool...
arch:
  - amd64
  - aarch64
url: "https://github.com/camiloconcha/homeassistant-addons"

# --- Sección añadida ---
options:
  port: 5678
  n8n_host: "localhost"
  n8n_protocol: "https"
schema:
  port:
    type: integer
  n8n_host:
    type: string
  n8n_protocol:
    type: string
# ------------------------

ports:
  5678/tcp: 5678      # Cámbialo a e.g. 8080 si prefieres otro puerto en el host
ports_description:
  5678/tcp: "Web Interface"

map:
  - type: addon_config
    read_only: false
    path: /home/node/

environment:
  PUID: "1"
  PGID: "1"
  N8N_SECURE_COOKIE: "false"
  TINI_SUBREAPER: "true"
  # --- Usamos los valores definidos en options ---
  N8N_HOST: "${n8n_host}"
  N8N_PROTOCOL: "${n8n_protocol}"
# ------------------------

image: docker.n8n.io/n8nio/n8n
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:5678]"
ingress: false
ingress_port: 5678
